### ISSUE TITLE
Couldn't find index page for 'eea.downloads' (maybe misspelled?)

### ISSUE THREAD

**Issue by davendal** [eea/eea.downloads#1]
This occurs consistently with Buildout with Plone 3.4.3 and 3.4.4 despite trying a range of workarounds.
Any help appreciated.

**Comment by avoinea** [comment]
Somehow we missed to release eea.downloads also on pypi. 
I fixed that: https://pypi.python.org/pypi/eea.downloads

Thank you for your report.

**Comment by davendal** [comment]
Thank you. Very much appreciated.
